name: "CI"
on:
  push:
    branches-ignore:
      - 'dependabot/**'
      - release
  pull_request:

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        # ubuntu-18.04 已经被 GitHub 弃用，这里更新到了最新的稳定版
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      # actions/checkout 更新到 v4
      - uses: actions/checkout@v4
      
      - name: Install GNU tar
        if: runner.os == 'macOS'
        run: |
          echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> $GITHUB_PATH
          
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        # `set-output` 语法已废弃，使用新的语法
        run: echo "dir=$(yarn cache dir)" >> "$GITHUB_OUTPUT"
        
      # actions/cache 更新到 v4
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ matrix.platform }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.platform }}-yarn-
            
      # actions/cache 更新到 v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            desktop/src-tauri/target
          key: ${{ matrix.platform }}-cargo-v2-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.platform }}-cargo-v2-
            
      # actions/setup-node 更新到 v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          # Node.js 12 也已经停止支持了，建议升级到 18 或更高版本
          node-version: 18
          
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: install tauri bundler
        if: runner.os != 'Windows'
        run: cargo install tauri-bundler || [ $? -eq 101 ]
        
      - name: install tauri bundler
        if: runner.os == 'Windows'
        run: cargo install tauri-bundler; exit ($LASTEXITCODE -ne 101 -and $LASTEXITCODE -ne 0)
        shell: powershell -command "& '{0}'"
        
      - name: install webkit2gtk (ubuntu only)
        # 同样更新 ubuntu 版本号
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0 squashfs-tools
          
      - name: install app dependencies
        run: yarn
        
      # https://github.com/tauri-apps/tauri-action/issues/162
      - name: build app
        run: cd desktop; yarn tauri:build
        
      - name: fake yarn
        run: node -e "eval(process.env.COMMAND)"
        env:
          COMMAND: 'fs.writeFileSync("desktop/yarn.lock","")'
          
      - uses: tauri-apps/tauri-action@v0
        with:
          npmScript: "tauri:build"
          projectPath: desktop/
          
      # actions/upload-artifact 更新到 v4
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact-${{ runner.os }}
          path: desktop/src-tauri/target/release/bundle
          
  test-web:
    # ubuntu-18.04 已经被 GitHub 弃用，这里更新到了最新的稳定版
    runs-on: ubuntu-22.04
    steps:
      # actions/checkout 更新到 v4
      - uses: actions/checkout@v4
      
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        # `set-output` 语法已废弃，使用新的语法
        run: echo "dir=$(yarn cache dir)" >> "$GITHUB_OUTPUT"
        
      # actions/cache 更新到 v4
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            
      # actions/setup-node 更新到 v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          # Node.js 12 也已经停止支持了，建议升级到 18 或更高版本
          node-version: 18
          
      - name: install app dependencies
        run: yarn
        
      - name: Build
        run: |
          yarn workspace we
